import type { Post } from "@/types";

const mockProfile = (id: string, username: string, displayName: string) => ({
  id,
  username,
  display_name: displayName,
  avatar_url: null,
  cover_url: null,
  bio: null,
  age: null,
  birthday: null,
  gender: null,
  pet_names: null,
  pet_types: null,
  is_private: false,
  created_at: "2024-01-01",
});

export const MOCK_POSTS: Post[] = [
  {
    id: "1",
    author_id: "u1",
    content:
      "Just adopted the fluffiest orange tabby 🧡 He spent the first hour knocking things off the shelf one by one, maintaining direct eye contact the whole time. I think we're going to get along perfectly.",
    image_url: null,
    like_count: 42,
    comment_count: 3,
    share_count: 1,
    shared_from_id: null,
    archived: false,
    archived_at: null,
    visibility: "public" as const,
    created_at: new Date(Date.now() - 1000 * 60 * 14).toISOString(),
    liked_by_me: false,
    my_reaction: null,
    pawmarked_by_me: false,
    author: mockProfile("u1", "mochi_mum", "Mochi's Mum"),
  },
  {
    id: "2",
    author_id: "u2",
    content:
      "PSA: if your cat stares at a wall at 3 AM, they're not seeing ghosts. They're planning something far worse.",
    image_url: null,
    like_count: 128,
    comment_count: 12,
    share_count: 4,
    shared_from_id: null,
    archived: false,
    archived_at: null,
    visibility: "public" as const,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    liked_by_me: true,
    my_reaction: "like",
    pawmarked_by_me: false,
    author: mockProfile("u2", "nyan_overlord", "Nyan Overlord"),
  },
  {
    id: "3",
    author_id: "u3",
    content:
      "Hot take: cats don't sleep 16 hours a day out of laziness. They're gathering energy for the 2 AM zoomies that will absolutely destroy your sleep schedule.",
    image_url: null,
    like_count: 77,
    comment_count: 5,
    share_count: 2,
    shared_from_id: null,
    archived: false,
    archived_at: null,
    visibility: "public" as const,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    liked_by_me: false,
    my_reaction: null,
    pawmarked_by_me: false,
    author: mockProfile("u3", "biscuit_maker", "Biscuit Maker"),
  },
  {
    id: "4",
    author_id: "u4",
    content:
      "My cat figured out how to open the treat drawer. I'd be mad but honestly I'm impressed. We respect the hustle in this household. 🐾",
    image_url: null,
    like_count: 214,
    comment_count: 18,
    share_count: 7,
    shared_from_id: null,
    archived: false,
    archived_at: null,
    visibility: "public" as const,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
    liked_by_me: false,
    my_reaction: null,
    pawmarked_by_me: false,
    author: mockProfile("u4", "purrfect_chaos", "Purrfect Chaos"),
  },
];
